port 26379

dir /tmp

sentinel resolve-hostnames yes
sentinel monitor kelora-platform-redis-master kelora-platform-redis-master 6379 $SENTINEL_QUORUM
sentinel down-after-milliseconds kelora-platform-redis-master $SENTINEL_DOWN_AFTER
sentinel parallel-syncs kelora-platform-redis-master 1
sentinel failover-timeout kelora-platform-redis-master $SENTINEL_FAILOVER
