spring:
  application:
    name: common-component
  datasource:
    url: '${KELARUS_DATABASE_URL:jdbc:postgresql://localhost:5434/kelarus_platform}'
    username: '${KELARUS_DATABASE_USERNAME}'
    password: '${KELARUS_DATABASE_PASSWORD}'
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.default_schema: common
  liquibase:
    change-log: classpath:liquibase/master.xml
    default-schema: common

server:
  port: ${SERVER_PORT:50004}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: '${KELARUS_EUREKA_URL:http://localhost:50001/eureka/}'
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true

    urls:
      - name: common-component
        url: /common-component/v3/api-docs

    urls-primary-name: common-component
