package id.com.flare.kelarus.component.constant;

public enum OtpTypeEnum {

    REGISTRATION, LOGIN, PASSWORD_RESET, PIN_RESET, VERIFICATION_CHANGE_MOBILE, VERIFICATION_CHANGE_EMAIL,
    VERIFICATION_EMAIL, VERIFICATION_PHONE_NUMBER;

}
