name: kelarus-platform

services:

  kelarus-platform-eureka-server:
    image: ${KELARUS_EUREKA_IMAGE:-kelarus-platform/eureka-server:local}
    container_name: kelarus-platform-eureka-server

    environment:
      SERVER_PORT: 50001
      KELARUS_EUREKA_HOSTNAME: eureka-server

    networks:
      kelarus-platform-network:
        aliases:
          - eureka-server


  kelarus-platform-api-gateway:
    image: ${KELARUS_API_GATEWAY_IMAGE:-kelarus-platform/api-gateway:local}
    container_name: kelarus-platform-api-gateway

    depends_on:
      kelarus-platform-eureka-server:
        condition: service_started

    environment:
      SERVER_PORT: 50002
      KELARUS_EUREKA_URL: http://eureka-server:50001/eureka/

    networks:
      kelarus-platform-network:
        aliases:
          - api-gateway


  kelarus-platform-account:
    image: ${KELARUS_ACCOUNT_IMAGE:-kelarus-platform/account:local}
    container_name: kelarus-platform-account

    depends_on:
      kelarus-platform-eureka-server:
        condition: service_started

      kelarus-platform-db:
        condition: service_healthy

    environment:
      SERVER_PORT: 50003

      KELARUS_EUREKA_URL: http://eureka-server:50001/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      KELARUS_DATABASE_URL: ${KELARUS_DATABASE_URL}
      KELARUS_DATABASE_USERNAME: ${KELARUS_DATABASE_USERNAME}
      KELARUS_DATABASE_PASSWORD: ${KELARUS_DATABASE_PASSWORD}

      KELARUS_AUTH_JWT_SECRET: ${KELARUS_AUTH_JWT_SECRET}

    networks:
      kelarus-platform-network:
        aliases:
          - account

  kelarus-platform-common:
    image: ${KELARUS_COMMON_IMAGE:-kelarus-platform/common:local}
    container_name: kelarus-platform-common

    depends_on:
      kelarus-platform-eureka-server:
        condition: service_started

      kelarus-platform-db:
        condition: service_healthy

    environment:
      SERVER_PORT: 50004

      KELARUS_EUREKA_URL: http://eureka-server:50001/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      KELARUS_DATABASE_URL: ${KELARUS_DATABASE_URL}
      KELARUS_DATABASE_USERNAME: ${KELARUS_DATABASE_USERNAME}
      KELARUS_DATABASE_PASSWORD: ${KELARUS_DATABASE_PASSWORD}

    networks:
      kelarus-platform-network:
        aliases:
          - common

  kelarus-platform-notification:
    image: ${KELARUS_NOTIFICATION_IMAGE:-kelarus-platform/notification:local}
    container_name: kelarus-platform-notification

    depends_on:
      kelarus-platform-eureka-server:
        condition: service_started

      kelarus-platform-db:
        condition: service_healthy

    environment:
      SERVER_PORT: 50005

      KELARUS_EUREKA_URL: http://eureka-server:50001/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      KELARUS_DATABASE_URL: ${KELARUS_DATABASE_URL}
      KELARUS_DATABASE_USERNAME: ${KELARUS_DATABASE_USERNAME}
      KELARUS_DATABASE_PASSWORD: ${KELARUS_DATABASE_PASSWORD}

    networks:
      kelarus-platform-network:
        aliases:
          - notification

  kelarus-platform-wms:
    image: ${KELARUS_WMS_IMAGE:-kelarus-platform/wms:local}
    container_name: kelarus-platform-wms

    depends_on:
      kelarus-platform-eureka-server:
        condition: service_started

      kelarus-platform-db:
        condition: service_healthy

    environment:
      SERVER_PORT: 50006

      KELARUS_EUREKA_URL: http://eureka-server:50001/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      KELARUS_DATABASE_URL: ${KELARUS_DATABASE_URL}
      KELARUS_DATABASE_USERNAME: ${KELARUS_DATABASE_USERNAME}
      KELARUS_DATABASE_PASSWORD: ${KELARUS_DATABASE_PASSWORD}

    networks:
      kelarus-platform-network:
        aliases:
          - wms

networks:
  kelarus-platform-network:
    name: kelarus-platform-network
