plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'kelarus-platform'

include 'component:account'
include 'component:common'
include 'component:notification'
include 'component:wms'
include 'component:api-gateway'
include 'component:eureka-server'
include 'utilities:general'
