services:

  kelarus-platform-eureka-server:
    build:
      context: ../../component/eureka-server
      dockerfile: Dockerfile

    ports:
      - "50001:50001"


  kelarus-platform-api-gateway:
    build:
      context: ../../component/api-gateway
      dockerfile: Dockerfile

    ports:
      - "50002:50002"


  kelarus-platform-account:
    build:
      context: ../../component/account
      dockerfile: Dockerfile

    ports:
      - "50003:50003"


  kelarus-platform-common:
    build:
      context: ../../component/common
      dockerfile: Dockerfile

    ports:
      - "50004:50004"


  kelarus-platform-notification:
    build:
      context: ../../component/notification
      dockerfile: Dockerfile

    ports:
      - "50005:50005"


  kelarus-platform-wms:
    build:
      context: ../../component/wms
      dockerfile: Dockerfile

    ports:
      - "50006:50006"
