# Kelora Platform Applications

name: kelora-platform-apps

services:

  # =========================
  # Eureka Server
  # =========================
  kelora-platform-eureka-server:
    image: kelora-platform/eureka-server

    container_name: kelora-platform-eureka-server

    ports:
      - "18102:18102"

    networks:
      - kelora-platform-network


  # =========================
  # API Gateway
  # =========================
  kelora-platform-api-gateway:
    image: kelora-platform/api-gateway

    container_name: kelora-platform-api-gateway

    depends_on:
      - kelora-platform-eureka-server

    environment:
      JAVA_TOOL_OPTIONS: >-
        -Deureka.client.serviceUrl.defaultZone=http://kelora-platform-eureka-server:18102/eureka

    ports:
      - "18100:18100"

    networks:
      - kelora-platform-network


# =========================
# Existing external network
# =========================
networks:
  kelora-platform-network:
    external: true
