# Kelarus Platform Applications

name: kelarus-platform-apps

services:

  # =========================
  # Eureka Server
  # =========================
  kelarus-platform-eureka-server:
    image: kelarus-platform/eureka-server

    container_name: kelarus-platform-eureka-server

    ports:
      - "18102:18102"

    networks:
      - kelarus-platform-network


  # =========================
  # API Gateway
  # =========================
  kelarus-platform-api-gateway:
    image: kelarus-platform/api-gateway

    container_name: kelarus-platform-api-gateway

    depends_on:
      - kelarus-platform-eureka-server

    environment:
      JAVA_TOOL_OPTIONS: >-
        -Deureka.client.serviceUrl.defaultZone=http://kelarus-platform-eureka-server:18102/eureka

    ports:
      - "18100:18100"

    networks:
      - kelarus-platform-network


# =========================
# Existing external network
# =========================
networks:
  kelarus-platform-network:
    external: true
