name: redis-cluster

x-redis-node: &redis-node
  image: redis:7
  command:
    - 'redis-server'
    - '--port 6379'
    - '--cluster-enabled yes'
    - '--cluster-config-file nodes.conf'
    - '--cluster-node-timeout 5000'
    - '--appendonly yes'
  healthcheck:
    test: ['CMD', 'redis-cli', 'ping']
    interval: 5s
    timeout: 3s
    retries: 10

services:
  kelora-platform-redis:
    <<: *redis-node
    ports:
      - '6379:6379'
    volumes:
      - kelora-platform-redis-0:/data
  kelora-platform-redis-1:
    <<: *redis-node
    ports:
      - '16379:6379'
    volumes:
      - kelora-platform-redis-1:/data
  kelora-platform-redis-2:
    <<: *redis-node
    ports:
      - '16380:6379'
    volumes:
      - kelora-platform-redis-2:/data
  kelora-platform-redis-3:
    <<: *redis-node
    ports:
      - '16381:6379'
    volumes:
      - kelora-platform-redis-3:/data
  kelora-platform-redis-4:
    <<: *redis-node
    ports:
      - '16382:6379'
    volumes:
      - kelora-platform-redis-4:/data
  kelora-platform-redis-5:
    <<: *redis-node
    ports:
      - '16383:6379'
    volumes:
      - kelora-platform-redis-5:/data
  kelora-platform-redis-cluster-builder:
    depends_on:
      kelora-platform-redis:
        condition: service_healthy
      kelora-platform-redis-1:
        condition: service_healthy
      kelora-platform-redis-2:
        condition: service_healthy
      kelora-platform-redis-3:
        condition: service_healthy
      kelora-platform-redis-4:
        condition: service_healthy
      kelora-platform-redis-5:
        condition: service_healthy
    build:
      context: .
      dockerfile: redis/Redis-Cluster.Dockerfile

volumes:
  kelora-platform-redis-0:
  kelora-platform-redis-1:
  kelora-platform-redis-2:
  kelora-platform-redis-3:
  kelora-platform-redis-4:
  kelora-platform-redis-5:
