name: redis-sentinel
services:
  kelora-platform-redis-master:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  kelora-platform-redis-slave:
    image: redis:7
    command:
      - 'redis-server'
      - '--slaveof kelora-platform-redis-master 6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  kelora-platform-redis-slave-1:
    image: redis:7
    command:
      - 'redis-server'
      - '--slaveof kelora-platform-redis-master 6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  kelora-platform-redis-sentinel-1:
    depends_on:
      kelora-platform-redis-master:
        condition: service_healthy
      kelora-platform-redis-slave:
        condition: service_healthy
      kelora-platform-redis-slave-1:
        condition: service_healthy
    build:
      context: .
      dockerfile: redis/Redis-Sentinel.Dockerfile
    ports:
      - '26379:26379'

  kelora-platform-redis-sentinel-2:
    depends_on:
      kelora-platform-redis-master:
        condition: service_healthy
      kelora-platform-redis-slave:
        condition: service_healthy
      kelora-platform-redis-slave-1:
        condition: service_healthy
    build:
      context: .
      dockerfile: redis/Redis-Sentinel.Dockerfile
    ports:
      - '26380:26379'

  kelora-platform-redis-sentinel-3:
    depends_on:
      kelora-platform-redis-master:
        condition: service_healthy
      kelora-platform-redis-slave:
        condition: service_healthy
      kelora-platform-redis-slave-1:
        condition: service_healthy
    build:
      context: .
      dockerfile: redis/Redis-Sentinel.Dockerfile
    ports:
      - '26381:26379'
