services:

  kelarus-platform-eureka-server:
    restart: always


  kelarus-platform-api-gateway:
    restart: always

    ports:
      - "127.0.0.1:50002:50002"


  kelarus-platform-account:
    restart: always


  kelarus-platform-common:
    restart: always


  kelarus-platform-notification:
    restart: always


  kelarus-platform-wms:
    restart: always
