plugins {
    id 'kelarus.infrastructure-conventions'
}

dependencies {
    compileOnly 'org.springframework:spring-webmvc'
    compileOnly 'org.springframework:spring-tx'
    compileOnly 'org.springframework.security:spring-security-core'
    compileOnly 'jakarta.validation:jakarta.validation-api'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    compileOnly "org.slf4j:slf4j-api:${slf4j_version}"
}
