spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: blocked-endpoints
          order: -100
          uri: no://op
          predicates:
            - Path=${GATEWAY_BLOCKED_PATHS:/internal/**}
          filters:
              - SetStatus=FORBIDDEN
        - id: account-component
          uri: lb://account-component
          predicates:
            - Path=/account-component/**
          filters:
            - RewritePath=/account-component(?<segment>/?.*), $\{segment}
        - id: swagger
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs(?<segment>/?.*), $\{segment}/v3/api-docs

server:
  port: ${SERVER_PORT:50002}

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: '${KELARUS_EUREKA_URL:http://localhost:50001/eureka/}'
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
